In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
import numpy
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

In [4]:
text = []
texts = []
import glob
filename ='Training text'
with open(filename) as f:
    text.append(f.readlines())
        
text = text[0]
text
for text in text:
    word_tokens = word_tokenize(text)
    filtered_sentence = [w for w in word_tokens if not w in stop_words]
    texts.append(filtered_sentence)
filtered_list = []
for text in texts:
    filtered_list.append(" ".join(text))
filtered_list

['An overview diabetes types treatments',
 'Last reviewed Thu 8 November 2018',
 'By Rachel Nall RN MSN',
 'Reviewed Suzanne Falck , MD , FACP',
 '1 . Types',
 '',
 '2 . How insulin problems develop',
 '',
 '3 . Exercise diet tips',
 '',
 '4 . Using insulin',
 '5 . Self-monitoring tips',
 '',
 '6 . Outlook',
 '',
 '7 . Takeaway',
 "Diabetes condition impairs body 's ability process blood glucose , otherwise known blood sugar .",
 'In United States , estimated number people 18 years age diagnosed undiagnosed diabetes 30.2 million . The figure represents 27.9 32.7 percent population .',
 'Without ongoing , careful management , diabetes lead buildup sugars blood , increase risk dangerous complications , including stroke heart disease .',
 'Different kinds diabetes occur , managing condition depends type . Not forms diabetes stem person overweight leading inactive lifestyle . In fact , present childhood .',
 'Types',
 '',
 'There several types diabetes .',
 'Three major diabetes types deve

In [10]:
filtered_list

[]

In [48]:
vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit_transform(filtered_list)
# used words (axis in our multi-dimensional space)
words = vectorizer.get_feature_names()
print("words", words)

words ['100', '125', '126', '18', '2018', '27', '30', '32', '40', '45', '50', '70', '99', 'ability', 'access', 'according', 'acting', 'active', 'activity', 'administers', 'aerobics', 'affects', 'african', 'age', 'alcohol', 'alive', 'allows', 'american', 'amounts', 'anesthesia', 'artificial', 'asian', 'assess', 'assessment', 'assuming', 'attack', 'attempt', 'available', 'avoiding', 'balanced', 'balances', 'benefits', 'better', 'bike', 'birth', 'bladder', 'bleeding', 'blood', 'bmi', 'body', 'bone', 'bones', 'borderline', 'bowel', 'buildup', 'called', 'calories', 'cancer', 'care', 'careful', 'carefully', 'case', 'cause', 'causes', 'causing', 'cells', 'certain', 'changes', 'check', 'checking', 'child', 'childhood', 'cholesterol', 'chronic', 'circulate', 'clearer', 'click', 'clicking', 'clots', 'combination', 'comes', 'common', 'completely', 'complication', 'complications', 'condition', 'conditions', 'confusion', 'cons', 'consistent', 'consistently', 'constitute', 'continue', 'control', 'co

C:\Users\WELCOME\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [49]:
n_clusters = 0
for _ in texts:
    n_clusters = n_clusters + 1
number_of_seeds_to_try=10
max_iter = 300
number_of_process=2 # seads are distributed
model = KMeans(n_clusters=n_clusters, max_iter=max_iter, n_init=number_of_seeds_to_try, n_jobs=number_of_process).fit(X)

In [50]:
labels = model.labels_
# indices of preferible words in each cluster
ordered_words = model.cluster_centers_.argsort()[:, ::-1]
n_clusters

124

In [51]:
print("centers:", model.cluster_centers_)
print("labels", labels)
print("intertia:", model.inertia_)

centers: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
labels [ 97  82  61  60 100   1  17   1  26   1   5   6   1  58   1  85  46  42
   0  77 100   1   2  86  88  48  91  15   9  50  32  40  29   8  43  74
  65  62  24  96  45  72  38  67  66  17  56  22  73  18  10  92   7  59
  26  30  37   1  80  12  36  69  84  53  49  47  89  75   5  23  16  54
  68  11  63   1  14  95  44   6  90  71  52  76   1  70  41  31  34  19
  99  25  83   1  93  27   4  94  21   4  20 101   4  57  21  33   1  78
  81   3  51  55  28  79  87  39   1  64  98   1   1  13   1  35]
intertia: 5.551115123125783e-16


In [52]:
texts_per_cluster = numpy.zeros(n_clusters)
for i_cluster in range(n_clusters):
    for label in labels:
        if label==i_cluster:
            texts_per_cluster[i_cluster] +=1 

In [53]:
print("Top words per cluster:")
for i_cluster in range(n_clusters):
    print("Cluster:", i_cluster, "texts:", int(texts_per_cluster[i_cluster])),
    for term in ordered_words[i_cluster, :10]:
        print("\t"+words[term])

Top words per cluster:
Cluster: 0 texts: 1
	buildup
	ongoing
	increase
	sugars
	careful
	disease
	management
	heart
	dangerous
	complications
Cluster: 1 texts: 15
	years
	fasting
	exercise
	exercising
	experience
	extra
	extremely
	facp
	fact
	factors
Cluster: 2 texts: 1
	types
	diabetes
	years
	fasting
	exercising
	experience
	extra
	extremely
	facp
	fact
Cluster: 3 texts: 1
	infection
	years
	fascinating
	exercise
	exercising
	experience
	extra
	extremely
	facp
	fact
Cluster: 4 texts: 3
	webmd
	years
	fasting
	exercise
	exercising
	experience
	extra
	extremely
	facp
	fact
Cluster: 5 texts: 2
	using
	insulin
	years
	exercise
	exercising
	experience
	extra
	extremely
	facp
	fact
Cluster: 6 texts: 2
	monitoring
	self
	tips
	fascinating
	exercise
	exercising
	experience
	extra
	extremely
	facp
Cluster: 7 texts: 1
	case
	attempt
	takes
	gradually
	place
	making
	slow
	cycle
	reverse
	recommend
Cluster: 8 texts: 1
	experience
	developing
	diabetes
	symptoms
	risk
	usually
	prediabetes
	peo

	eat
	diet
	levels
	people
Cluster: 105 texts: 0
	buildup
	ongoing
	increase
	sugars
	careful
	disease
	management
	heart
	dangerous
	complications
Cluster: 106 texts: 0
	kinds
	leading
	childhood
	stem
	fact
	managing
	inactive
	depends
	present
	forms
Cluster: 107 texts: 0
	100
	range
	borderline
	milligrams
	deciliter
	125
	refer
	dl
	mg
	doctors
Cluster: 108 texts: 0
	dl
	mg
	sugar
	blood
	70
	99
	normal
	sit
	fasting
	126
Cluster: 109 texts: 0
	45
	years
	age
	fasting
	exercising
	experience
	extra
	extremely
	facp
	fact
Cluster: 110 texts: 0
	insulin
	food
	following
	supply
	allows
	energy
	access
	result
	cycle
	resistance
Cluster: 111 texts: 0
	person
	specialist
	nutritionist
	balanced
	refer
	active
	diabetes
	doctor
	condition
	manage
Cluster: 112 texts: 0
	treat
	clicking
	manage
	learn
	diabetes
	extra
	extremely
	experience
	fasting
	facp
Cluster: 113 texts: 0
	people
	type
	inject
	inhale
	diabetes
	high
	need
	levels
	sugar
	blood
Cluster: 114 texts: 0
	acting
	use
	in

In [54]:
print("\n")
print("Prediction")

text_to_predict = "This is the most common surgery for chronic nonspecific back pain with degenerative changes."
Y = vectorizer.transform([text_to_predict])
predicted_cluster = model.predict(Y)[0]
texts_per_cluster[predicted_cluster]+=1



Prediction


C:\Users\WELCOME\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [55]:
print(text_to_predict)
print("Cluster:", predicted_cluster, "texts:", int(texts_per_cluster[predicted_cluster])),
for term in ordered_words[predicted_cluster, :10]:
    print("\t"+words[term])

This is the most common surgery for chronic nonspecific back pain with degenerative changes.
Cluster: 1 texts: 16
	years
	fasting
	exercise
	exercising
	experience
	extra
	extremely
	facp
	fact
	factors


In [2]:
from gensim.test.utils import datapath

C:\Users\WELCOME\Anaconda3\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [3]:
#Import all the dependencies
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize
import gensim


##with open("C:\\Users\\WELCOME\\Desktop\\Traning\\CleansedFile.txt", "w") as fobj:
##    for x in filtered_list:
##        fobj.write(x + "\n")

C:\Users\WELCOME\Anaconda3\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [5]:
sentences = gensim.models.word2vec.Text8Corpus(datapath('C:\\Users\\WELCOME\\Desktop\\Traning\\CleansedFile.txt'))

In [6]:
sentences

In [9]:
tagged_data = [TaggedDocument(words=word_tokenize(_d.lower()), tags=[str(i).lower()]) for i, _d in enumerate(filtered_list)]

In [10]:
max_epochs = 200
vec_size = 20
alpha = 0.025

model = Doc2Vec(size=vec_size,
                alpha=alpha, 
                min_alpha=0.00025,
                min_count=1,
                dm =1)
model.build_vocab(tagged_data)

C:\Users\WELCOME\Anaconda3\lib\site-packages\gensim\models\doc2vec.py:570: UserWarning: The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.
  warnings.warn("The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.")


In [11]:
for epoch in range(max_epochs):
    print('iteration {0}'.format(epoch))
    model.train(tagged_data,
                total_examples=model.corpus_count,
                epochs=model.iter)
    # decrease the learning rate
    model.alpha -= 0.0002
    # fix the learning rate, no decay
    model.min_alpha = model.alpha

model.save("d2v.model")
print("Model Saved")

iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7


C:\Users\WELCOME\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  """


iteration 8
iteration 9
iteration 10
iteration 11
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
iteration 18
iteration 19
iteration 20
iteration 21
iteration 22
iteration 23
iteration 24
iteration 25
iteration 26
iteration 27
iteration 28
iteration 29
iteration 30
iteration 31
iteration 32
iteration 33
iteration 34
iteration 35
iteration 36
iteration 37
iteration 38
iteration 39
iteration 40
iteration 41
iteration 42
iteration 43
iteration 44
iteration 45
iteration 46
iteration 47
iteration 48
iteration 49
iteration 50
iteration 51
iteration 52
iteration 53
iteration 54
iteration 55
iteration 56
iteration 57
iteration 58
iteration 59
iteration 60
iteration 61
iteration 62
iteration 63
iteration 64
iteration 65
iteration 66
iteration 67
iteration 68
iteration 69
iteration 70
iteration 71
iteration 72
iteration 73
iteration 74
iteration 75
iteration 76
iteration 77
iteration 78
iteration 79
iteration 80
iteration 81
iteration 82
iteration 83
iteration 84
i

In [2]:
from gensim.models.doc2vec import Doc2Vec

model= Doc2Vec.load("d2v.model")
#to find the vector of a document which is not in training data
test_data = word_tokenize("I love chatbots".lower())
v1 = model.infer_vector(test_data)
print("V1_infer", v1)

# to find most similar doc using tags
print('Similar Doc')
similar_doc = model.docvecs.most_similar('1')
print(similar_doc)
print(model)


# to find vector of doc in training data using tags or in other words, printing the vector of document at index 1 in training data
print(model.docvecs['1'])

V1_infer [ 0.02531308  0.01739571  0.02567057  0.00428392  0.03078081  0.02595692
 -0.00054111 -0.00156914 -0.04392874 -0.01748489  0.0086702  -0.00249651
  0.02169421 -0.02446095  0.01836913  0.00924655 -0.03711869 -0.00947814
  0.03177491  0.00380384]
Similar Doc
[('3', 0.8138267397880554), ('113', 0.7016131281852722), ('87', 0.6488231420516968), ('36', 0.6187425851821899), ('103', 0.606508195400238), ('99', 0.5908279418945312), ('102', 0.5885677933692932), ('96', 0.5879293084144592), ('97', 0.5849944353103638), ('98', 0.5834324359893799)]
[ 1.136694    0.84360754  1.3676888  -0.4100031   2.2588863   2.094213
 -0.5070193   1.4873129  -0.15604031 -1.4623159   0.96231765 -1.4839758
 -0.98616517  1.1545292   2.564977   -2.169538   -1.2557262   1.7247679
  2.3497164   0.41011253]


C:\Users\WELCOME\Anaconda3\lib\site-packages\gensim\matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int32 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [6]:
import gensim
model = gensim.models.Doc2Vec.load('d2v.model') 

In [7]:
new_sentence = "Diabetes".lower().split(" ")  
similar_phrase = model.docvecs.most_similar(positive=[model.infer_vector(new_sentence)],topn=3)
similar_phrase

C:\Users\WELCOME\Anaconda3\lib\site-packages\gensim\matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int32 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('63', 0.47641655802726746),
 ('50', 0.44175606966018677),
 ('38', 0.41870829463005066)]

In [8]:
tagged_data[int('24')][0]

['type',
 'i',
 'diabetes',
 ':',
 'also',
 'known',
 'juvenile',
 'diabetes',
 ',',
 'type',
 'occurs',
 'body',
 'fails',
 'produce',
 'insulin',
 '.',
 'people',
 'type',
 'i',
 'diabetes',
 'insulin-dependent',
 ',',
 'means',
 'must',
 'take',
 'artificial',
 'insulin',
 'daily',
 'stay',
 'alive',
 '.']

In [12]:
tagged_data

[TaggedDocument(words=['an', 'overview', 'diabetes', 'types', 'treatments'], tags=['0']),
 TaggedDocument(words=['last', 'reviewed', 'thu', '8', 'november', '2018'], tags=['1']),
 TaggedDocument(words=['by', 'rachel', 'nall', 'rn', 'msn'], tags=['2']),
 TaggedDocument(words=['reviewed', 'suzanne', 'falck', ',', 'md', ',', 'facp'], tags=['3']),
 TaggedDocument(words=['1', '.', 'types'], tags=['4']),
 TaggedDocument(words=[], tags=['5']),
 TaggedDocument(words=['2', '.', 'how', 'insulin', 'problems', 'develop'], tags=['6']),
 TaggedDocument(words=[], tags=['7']),
 TaggedDocument(words=['3', '.', 'exercise', 'diet', 'tips'], tags=['8']),
 TaggedDocument(words=[], tags=['9']),
 TaggedDocument(words=['4', '.', 'using', 'insulin'], tags=['10']),
 TaggedDocument(words=['5', '.', 'self-monitoring', 'tips'], tags=['11']),
 TaggedDocument(words=[], tags=['12']),
 TaggedDocument(words=['6', '.', 'outlook'], tags=['13']),
 TaggedDocument(words=[], tags=['14']),
 TaggedDocument(words=['7', '.', 'ta